openapi: 3.0.0
info:
  title: Green Cart
  version: 1.0.0
  description: This are the API's of the MyGainn 

security:
  - bearerAuth: []     


# Start API

paths:
  /api:
    get:
      tags:
        - Home
      description: Home
      responses:
        "200":
         description: Home Page
        "401":
         description: Something is wrong
  
  /user/login:
    post:
      tags:
          - Login
      parameters:
        - name: Email
          in:  query
          description: Please Enter Your Email
          required: true
          schema:
            type: string
        - name:  Password
          in: query
          description: Please Enter Your Password
          schema:
            type: string
      responses:
         200:
          description: Success
         400:
          description: Bad Request








# componenets

components:
  requestBodies:
    Pet:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
         